name: Print RSS

on:
  rss:
    url: https://www.reddit.com/r/freebooks/.rss
    source: json

jobs:
  print_rss:
    name: Print RSS Data
    runs-on: ubuntu-latest
    steps:
      - name: Print RSS
        run: |
          echo "Title: ${{on.rss.outputs.title}}"
          echo "Link: ${{on.rss.outputs.link}}"
          echo "Content Snippet: $contentSnippet"

