name: Print RSS

on:
  rss:
    url: https://www.reddit.com/r/freebooks/.rss

jobs:
  print_rss:
    name: Print RSS Data
    runs-on: ubuntu-latest
    cache: 'npm' 
    steps:
      - name: Print RSS
        run: |
          echo "contentSnippet :${{on.rss.outputs.contentSnippet}}"
          echo "<a href=\"${{on.rss.outputs.link}}\">${{on.rss.outputs.title}}</a>"
          echo "by: ${{on.rss.outputs.author}}"
          echo "Title: ${{on.rss.outputs.title}}"
          echo "<a href=\"${{on.rss.outputs.link}}\">${{on.rss.outputs.title}}</a>"
          echo "Content: ${{on.rss.outputs.content}}"
          echo "by: ${{on.rss.outputs.author}}"
#| sed 's/<br\/>//g')
