name: RSS to Print

on:
  rss:
    url: https://www.reddit.com/r/freebooks/.rss
    source: json

jobs:
  print_items:
    name: Print RSS Items
    runs-on: ubuntu-latest
    steps:
      - name: Print RSS Item Details
        run: |
          echo "Title: ${{ on.rss.outputs.title }}"
          echo "Subreddit: ${{ on.rss.outputs.subreddit }}"
          echo "Content: ${{ on.rss.outputs.content }}"
          echo "Selftext: ${{ on.rss.outputs.selftext }}"
          echo "Author Fullname: ${{ on.rss.outputs.author_fullname }}"
          echo "Subreddit Name Prefixed: ${{ on.rss.outputs.subreddit_name_prefixed }}"
          echo "Post Hint: ${{ on.rss.outputs.post_hint }}"
          echo "Domain: ${{ on.rss.outputs.domain }}"
          echo "Permalink: ${{ on.rss.outputs.permalink }}"
          echo "URL: ${{ on.rss.outputs.url }}"
