name: Reddit to Print
on:
  rss:
    url: https://www.reddit.com/r/buildapc/.rss
    source: json
  
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
      format: HTML
        env:
          message: |
          title: <b>${{ on.rss.outputs.title }}</b>
          contentSnippet:  Via <a href="https://reddit.com/${{ on.rss.outputs.permalink }}">{{{ on.rss.outputs.subreddit_name_prefixed }}</a> By ${{ on.rss.outputs.author }}
          link:  <a href="${{ on.rss.outputs.url_overridden_by_dest }}">Book Link</a>
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
