name: rss to print

on:
  rss:
    url: https://www.reddit.com/r/buildapc/.rss
    source: json
  
jobs:
  print:
    name: Print RSS Data
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install jq -y

      - name: Print RSS Data
        run: |
          echo "Title: ${{ toJson(on.rss.data.children[0].data.title) }}"
          echo "Permalink: ${{ toJson(on.rss.data.children[0].data.permalink) }}"
          echo "Subreddit: ${{ toJson(on.rss.data.children[0].data.subreddit_name_prefixed) }}"
          echo "Author: ${{ toJson(on.rss.data.children[0].data.author) }}"
          echo "URL: ${{ toJson(on.rss.data.children[0].data.url_overridden_by_dest) }}"
