name: Print RSS

on:
  rss:
    url: https://www.reddit.com/r/csi/.rss
    source: json

jobs:
  print_rss:
    name: Print RSS Data
    runs-on: ubuntu-latest
    steps:
      - name: Print RSS
        run: |
          contentSnippet=$(echo "${{on.rss.outputs.contentSnippet}}" | sed 's/<br\/>/\n/g')
          echo "Title: ${{on.rss.outputs.title}}"
          echo "Content Snippet: $contentSnippet"
          echo "Link: ${{on.rss.outputs.link}}"

