on:
  rss:
    url: https://www.reddit.com/r/FreeEBOOKS/.rss
jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Fetch RSS data
        uses: actionsflow/actionsflow-action@v1.3.0
        with:
          config: rss
          config_source: json
          config_url: 'https://hnrss.org/newest?points=300&count=3'

      - name: Print Outputs
        env:
          title: ${{ steps.fetch.outputs.title }}
          contentSnippet: ${{ steps.fetch.outputs.contentSnippet }}
          link: ${{ steps.fetch.outputs.link }}
        run: |
          echo title: $title
          echo contentSnippet: $contentSnippet
          echo link: $link
