name: RSS to Print

on:
  cron: "*/15 * * * *" # Executa a cada 15 minutos

jobs:
  rss_to_print:
    name: RSS to Print
    runs-on: ubuntu-latest
    steps:
      - name: Fetch RSS data
        uses: actionsflow/actionsflow-action@v1.3.0
        with:
          config: rss
          config_source: json
          config_url: "https://www.reddit.com/r/buildapc"

      - name: Print RSS Content
        run: |
          echo "Title: ${{on.rss.outputs.title}}"
          echo "Content Snippet: ${{on.rss.outputs.contentSnippet}}"
          echo "Link: ${{on.rss.outputs.link}}"
