name: rss to telegram

on:
  rss:
    url: https://www.reddit.com/r/FreeEBOOKS+freebooks/.rss
    source: json
  
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: HTML
          disable_web_page_preview: true
          message: |
            <b>${{ on.rss.outputs.title }}</b>
            Via <a href="https://reddit.com/${{ on.rss.outputs.permalink }}">{{ on.rss.outputs.subreddit_name_prefixed }}</a> By ${{ on.rss.outputs.author }}
            <a href="${{ on.rss.outputs.url_overridden_by_dest }}">Book Link</a>
